src/projects/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from projects.views import ProjectsListView, ProjectDetailView, JoinProjectView
from images.views import ImageLabelUpdateView

urlpatterns = [
    url(r'^$', ProjectsListView.as_view(), name='projects-list'),
    url(r'^(?P<slug>[-\w]+)/?$', ProjectDetailView.as_view(), name='porject-detail'),
    url(r'^(?P<slug>[-\w]+)/join/?$', JoinProjectView.as_view(), name='join-project'),
    url(r'^[-\w]+/image/(?P<pk>[0-9]+)/?$', ImageLabelUpdateView.as_view(), name='image-label-update'),
]

src/timlab/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^p/', include('projects.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/projects/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User


@python_2_unicode_compatible
class Project(models.Model):
    """
    Image labeling project
    """
    
    slug = models.SlugField(unique=True, blank=True,
        help_text="Will be provided automaticly if left blank.")
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True,
        help_text="Can contain HTML. Will be placed inside a DIV element.")
    is_active = models.BooleanField(default=False,
        help_text="Enable project when it is ready for labeling.")
    train_count = models.IntegerField(verbose_name="Training image count",
        help_text="Number of images to show for a single user.")
    created = models.DateTimeField(auto_now_add=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        
        super(Project, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.title
    

@python_2_unicode_compatible
class Label(models.Model):
    """
    Labels available in a project
    """
    
    text = models.CharField(max_length=50,
        help_text="Short text shown as a choice.")
    code = models.CharField(max_length=20, blank=True,
        help_text="Unique code representing this label.")
    description = models.TextField(blank=True,
        help_text="Longer description to explain meaning of label." +
        "Can contain HTML. Will be placed inside a DIV element.")
    project = models.ForeignKey(Project,
        help_text="A project offering this label as a choice to user.")
    
    class Meta:
        unique_together = ('code', 'project')
        
    def save(self, *args, **kwargs):
        if not self.code:
            self.code = slugify(self.text)
        
        super(Label, self).save(*args, **kwargs)
    
    def __str__(self):
        if self.code:
            return "%s (%s - %s)" % (self.text, self.code, self.project.title)
        return "%s (%s)" % (self.text, self.project.title)

@python_2_unicode_compatible
class UsersProject(models.Model):
    """
    Links Users with Projects
    """
    
    completed_imgs = models.IntegerField(default=0,
        help_text="How many images have been labeled.")
    user = models.ForeignKey(User)
    project = models.ForeignKey(Project)
    joined = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return "%s - %s" % (self.user.username, self.project.title)
    
    def get_complete_percent(self):
        return round((self.completed_imgs * 100.0) / self.project.train_count, 1)

src/projects/views.py
# -*- coding: utf-8 -*-
from random import sample

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render

from projects.models import Project, UsersProject
from images.models import ImageLabel, Image


class ProjectsListView(ListView):
    model = Project
    order = ('is_active', 'created')


class ProjectDetailView(DetailView):
    model = Project
    
    def get_unlabeled(self):
        """
        Returns URL of one of unlabeled images for particular user
        """
        
        if not self.request.user:
            return None
        
        im_pk = ImageLabel.objects.filter(user=self.request.user, label__isnull=True).values_list('id', flat=True).first()
        if im_pk:
            return '/p/%s/image/%s/' % (self.object.slug, im_pk)
        else:
            return None
    
    def get_usersproject(self):
        """
        Return userproject object for current user
        """
        if not self.request.user:
            return None
        
        up = UsersProject.objects.filter(user=self.request.user, project=self.object).first()
        return up


class JoinProjectView(LoginRequiredMixin, TemplateView):
    template_name = 'projects/project_join.html'
    
    def post(self, request, *args, **kwargs):
        try:
            project = Project.objects.get(slug=kwargs['slug'])
        except Project.DoesNotExist:
            raise Http404("Project does not exist!")
        
        up = UsersProject.objects.filter(user=self.request.user, project=project).first()
        if up:
            return render(request, self.template_name, {
                'message': "You already have joined this project.",
                'project': project
            })
        
        up = UsersProject(user=self.request.user, project=project)
        up.save()
        
        im_set = Image.objects.filter(project=project)
        # Choose random images from all available
        im_ids = sample(xrange(len(im_set)), project.train_count)
        for i in im_ids:
            il = ImageLabel(image=im_set[i], user=self.request.user, project=project)
            il.save()
        
        return render(request, self.template_name, {
            'message': "You have joined the %s project!" % (project.title),
            'project': project,
            'first_img': '/p/%s/image/%s/' % (project.slug, il.pk)
        })

src/projects/templates/projects/project_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title }}{% endblock %}

{% block nav-menu %}<li class="active"><a href="/p/{{ object.slug }}/">{{ object.title }}</a></li>{% endblock %}

{% block header %}
<style type="text/css">
    div.modal-content { padding: 1em; }
</style>
{% endblock %}

{% block content %}
<h1>{{ object.title }} <span class="label label-{{ object.is_active|yesno:'success,default' }}">{{ object.is_active|yesno:'Active,Inactive' }}</span></h1>
<small>Created on {{ object.created }}</small>
<p class="well">{{ object.description|safe }}</p>
{% if user.is_authenticated %}
{% if not view.get_usersproject %}
<div id="join-modal" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            Assigning images. Please wait...
        </div>
    </div>
</div>
<form id="join-project" action="{% url 'join-project' object.slug %}" method="post">
    {% csrf_token %}
    <div class="alert alert-info">You must join this project to start labeling images:
    <button class="btn btn-primary" type="submit" data-toggle="modal" data-target="#join-modal">Join this project</button></div>
</form>
{% endif %}
{% if view.get_unlabeled %}
<div class="alert alert-info"><a href="{{ view.get_unlabeled }}" class="btn btn-primary btn" role="button">Label images</a></div>
{% endif %}
{% else %}
    <p class="bg-info">You must log in to participate.</p>
{% endif %}
<div>
    <ul class="list-group">In this project you will be asked to classify small pictures into one of following classes:
        {% for k in project.label_set.all %}
        <li class="list-group-item">{{ k.text }}{% if k.code %} ({{ k.code }}){% endif %}
            <span class="tip-content">– {{ k.description|safe }}</span></li>
        {% empty %}
        <li class="list-group-item bg-info">No labeling classes have been defined</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

src/projects/templates/projects/project_join.html
{% extends "base.html" %}

{% block title %}Join {{ project.title }}{% endblock %}

{% block nav-menu %}<li class="active"><a href="/p/{{ project.slug }}/">{{ project.title }}</a></li>{% endblock %}

{% block content %}
<h1>Join {{ project.title }}</h1>
<p class="alert alert-info">{{ message }}</p>
{% if first_img %}
<div class="alert alert-success">
    <a href="{{ first_img }}" class="btn btn-primary btn" role="button">Start labeling</a>
</div>
{% endif %}
{% endblock %}

src/projects/templates/projects/project_list.html
{% extends "base.html" %}

{% block title %}List of projects{% endblock %}

{% block project_list_class %}active{% endblock %}

{% block content %}
<div class="container-fluid">
    {% for project in object_list %}
    <div class="col-md-5">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="h3"><a href="/p/{{ project.slug }}/">{{ project.title }}</a></span> <span class="label label-{{ project.is_active|yesno:'success,default' }}">{{ project.is_active|yesno:'Active,Inactive' }}</span></div>
            <div class="panel-body">
                <p>{{ project.description|safe }}</p>
            </div>
        </div>
    </div>
    {% empty %}
    <p class="bg-info">There are no projects defined yet.</p>
    {% endfor %}
</div>
{% endblock %}